### ISSUE TITLE
Template rules error - filter iterator error

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-h#22] opened 2016-03-29 22:39 UTC
The slope and aspect rules both generate the "Unable to open the input raster" error when the filter iterators are activated. The same issue might exist in other rules that involve the filter operation.

**Comment by lbross** [comment] 2016-03-29 23:45
This code has been working fine since the original BAGIS. I suspect it is a bug introduced with v10.2.2. The code fails during the third pass through a loop when filtering when it has to open the raster from memory for the first time. Since this is the old ESRI Geoanalyst ArcObjects API, I doubt they will fix it. I have tried explicitly setting the output workspace which didn't help. Next step is to try saving to disk and opening each time. If that doesn't work, Geoprocessor. Either way, it will be slower :-(

**Comment by lbross** [comment] 2016-03-31 18:38
I have made some progress on this. A couple of things seemed to be broken after switching to 10.2.2. One that I am still struggling with is applying the the mask to the IRasterAnalysisEnvironment. For some reason, when we do this, the Focal Statistics operation fails on the third pass through. My guess is that it is holding a file open. 

How important is applying the mask in the BA_AddRasFilter function? If I can figure out a way to apply it on only the first pass through, does that work? If I clip the output to the mask after the filtering, might that work?

**Comment by jdduh** [comment] 2016-03-31 19:06
The mask, if I remember correctly, is to make sure the output won't include areas in the buffered zones that might result in reporting wrong AOI numbers. I think by "clipping" the input course layer, be it PRISM, DEM, slope, etc, would solve the problem. Have you checked if there is an IRasterAnalysisEnvironment2 available?

**Comment by lbross** [comment] 2016-03-31 19:50
No IRasterAnalysisEnvironment2 interface. Will clip the input layer before filtering. Shouldn't add too much processing.

**Comment by lbross** [comment] 2016-03-31 22:33
This is fixed. New version of add-in available [here](https://github.com/PSU-CSAR/vb-bagis-h/releases/tag/1.6.2)

**Comment by jdduh** [comment] 2016-03-31 23:03
Please verify that the other template rules that also implement the iterative filtering are fixed as well. Thanks!

**Comment by lbross** [comment] 2016-04-01 18:24
I added some additional error handling and validated that are template rules are working as designed.

**Comment by lbross** [comment] 2016-04-20 00:08
Closing per @jdduh

**Closed by lbross** 2016-04-20 00:08 UTC
Labels: bug
